In [1]:
import os
import pandas as pd

In [2]:
dfs = []

for f in os.listdir("with_legacy_format"):
    if f.endswith(".csv"):
        df = pd.read_csv(f"with_legacy_format/{f}", sep=",", dtype={"energy_consumed": float, "emissions": float})
        dfs.append(df)

with_legacy_format_dfs = pd.concat(dfs)
with_legacy_format_dfs.head()

with_legacy_format_average_df = with_legacy_format_dfs.groupby("project_name")[["energy_consumed", "emissions"]].mean().reset_index()
with_legacy_format_average_df.head(21)

                                      project_name  energy_consumed  emissions
0                                  test_date_logic         0.000035   0.000015
1     test_do_change_user_setting_presence_enabled         0.000060   0.000025
2                                test_email_access         0.000043   0.000018
3               test_filter_presence_idle_user_ids         0.000032   0.000013
4                                test_get_statuses         0.000062   0.000026
5                      test_history_limit_days_api         0.000035   0.000015
6                            test_invalid_presence         0.000023   0.000010
7                          test_last_update_id_api         0.000023   0.000010
8       test_last_update_id_api_no_data_edge_cases         0.000021   0.000009
9                        test_last_update_id_logic         0.000050   0.000021
10                             test_new_user_input         0.000051   0.000022
11                   test_null_timestamps_handling         0.000049   0.000021
12                                  test_ping_only         0.000033   0.000014
13                          test_presence_disabled         0.000038   0.000016
14                      test_pushable_always_false         0.000031   0.000013
15                               test_query_counts         0.000045   0.000019
16                                 test_same_realm         0.000048   0.000020
17                                 test_set_active         0.000049   0.000021
18                                   test_set_idle         0.000050   0.000021
19                            test_single_user_get         0.000052   0.000022
20  test_user_presence_row_creation_simulated_race         0.000023   0.000010

In [3]:
dfs = []

for f in os.listdir("without_legacy_format"):
    if f.endswith(".csv"):
        df = pd.read_csv(f"without_legacy_format/{f}", sep=",", dtype={"energy_consumed": float, "emissions": float})
        dfs.append(df)

without_legacy_format_dfs = pd.concat(dfs)
without_legacy_format_dfs.head()

without_legacy_format_average_df = without_legacy_format_dfs.groupby("project_name")[["energy_consumed", "emissions"]].mean().reset_index()
without_legacy_format_average_df.head(21)

,project_name,energy_consumed,emissions
0,test_date_logic,0.000002,1.110675e-06
1,test_do_change_user_setting_presence_enabled,0.000002,9.177235e-07
2,test_email_access,0.000003,1.454438e-06
3,test_filter_presence_idle_user_ids,0.000003,1.497669e-06
4,test_get_statuses,0.000019,8.754268e-06
5,test_history_limit_days_api,0.000005,2.205036e-06
6,test_invalid_presence,0.000001,5.266986e-07
7,test_last_update_id_api,0.000005,2.424116e-06
8,test_last_update_id_api_no_data_edge_cases,0.000002,8.511371e-07
9,test_last_update_id_logic,0.000003,1.366479e-06
10,test_new_user_input,0.000005,2.444761e-06
11,test_null_timestamps_handling,0.000003,1.213618e-06
12,test_ping_only,0.000002,7.687463e-07
13,test_presence_disabled,0.000003,1.361824e-06
14,test_pushable_always_false,0.000002,8.491922e-07
15,test_query_counts,0.000002,1.056702e-06
16,test_same_realm,0.000003,1.434015e-06
17,test_set_active,0.000004,2.003290e-06
18,test_set_idle,0.000003,1.218818e-06
19,test_single_user_get,0.000029,1.307415e-05
20,test_user_presence_row_creation_simulated_race,0.000002,7.149462e-07

In [4]:
difference = with_legacy_format_average_df[['project_name']].copy()
difference[["energy_consumed", "emissions"]] = with_legacy_format_average_df[["energy_consumed", "emissions"]] - without_legacy_format_average_df[["energy_consumed", "emissions"]]
difference.head(21)

                                      project_name  energy_consumed  emissions
0                                  test_date_logic         0.000032   0.000014
1     test_do_change_user_setting_presence_enabled         0.000058   0.000024
2                                test_email_access         0.000040   0.000017
3               test_filter_presence_idle_user_ids         0.000028   0.000012
4                                test_get_statuses         0.000043   0.000018
5                      test_history_limit_days_api         0.000030   0.000013
6                            test_invalid_presence         0.000021   0.000009
7                          test_last_update_id_api         0.000018   0.000007
8       test_last_update_id_api_no_data_edge_cases         0.000019   0.000008
9                        test_last_update_id_logic         0.000047   0.000020
10                             test_new_user_input         0.000046   0.000019
11                   test_null_timestamps_handling         0.000047   0.000020
12                                  test_ping_only         0.000031   0.000013
13                          test_presence_disabled         0.000035   0.000015
14                      test_pushable_always_false         0.000029   0.000012
15                               test_query_counts         0.000043   0.000018
16                                 test_same_realm         0.000045   0.000019
17                                 test_set_active         0.000044   0.000019
18                                   test_set_idle         0.000047   0.000020
19                            test_single_user_get         0.000023   0.000009
20  test_user_presence_row_creation_simulated_race         0.000022   0.000009

In [8]:
difference_in_percentage = with_legacy_format_average_df[['project_name']].copy()
difference_in_percentage[["energy_consumed", "emissions"]] = ((with_legacy_format_average_df[["energy_consumed", "emissions"]] - without_legacy_format_average_df[["energy_consumed", "emissions"]]) / with_legacy_format_average_df[["energy_consumed", "emissions"]]) * 100
difference_in_percentage = difference_in_percentage.rename(
    columns={
        "energy_consumed": "energy_consumed_percentage_change",
        "emissions": "emissions_percentage_change"
    }
)
difference_in_percentage["energy_consumed_percentage_change"] = difference_in_percentage["energy_consumed_percentage_change"].round(1).astype(str) + "%"
difference_in_percentage["emissions_percentage_change"] = difference_in_percentage["emissions_percentage_change"].round(1).astype(str) + "%"
difference_in_percentage.head(21)

,project_name,energy_consumed_percentage_change,emissions_percentage_change
0,test_date_logic,92.9%,92.4%
1,test_do_change_user_setting_presence_enabled,96.6%,96.4%
2,test_email_access,92.5%,92.0%
3,test_filter_presence_idle_user_ids,89.6%,88.8%
4,test_get_statuses,69.0%,66.8%
5,test_history_limit_days_api,86.0%,85.1%
6,test_invalid_presence,94.9%,94.5%
7,test_last_update_id_api,76.9%,75.3%
8,test_last_update_id_api_no_data_edge_cases,90.9%,90.3%
9,test_last_update_id_logic,93.9%,93.5%
10,test_new_user_input,89.4%,88.7%
11,test_null_timestamps_handling,94.6%,94.2%
12,test_ping_only,94.9%,94.5%
13,test_presence_disabled,92.2%,91.6%
14,test_pushable_always_false,93.8%,93.4%
15,test_query_counts,94.9%,94.5%
16,test_same_realm,93.4%,92.9%
17,test_set_active,90.9%,90.2%
18,test_set_idle,94.6%,94.2%
19,test_single_user_get,44.5%,40.6%
20,test_user_presence_row_creation_simulated_race,93.2%,92.8%