In [1]:
import os
import pandas as pd

In [2]:
dfs = []

for f in os.listdir("with_legacy_format"):
    if f.endswith(".csv"):
        df = pd.read_csv(f"with_legacy_format/{f}", sep=",", dtype={"energy_consumed": float, "emissions": float})
        dfs.append(df)

with_legacy_format_dfs = pd.concat(dfs)
with_legacy_format_dfs.head()

with_legacy_format_average_df = with_legacy_format_dfs.groupby("project_name")[["energy_consumed", "emissions"]].mean().reset_index()
with_legacy_format_average_df.head(20)

                                      project_name  energy_consumed  emissions
0                                  test_date_logic         0.000003   0.000001
1     test_do_change_user_setting_presence_enabled         0.000003   0.000001
2                                test_email_access         0.000003   0.000001
3               test_filter_presence_idle_user_ids         0.000003   0.000001
4                      test_history_limit_days_api         0.000003   0.000001
5                            test_invalid_presence         0.000003   0.000001
6                          test_last_update_id_api         0.000004   0.000001
7       test_last_update_id_api_no_data_edge_cases         0.000003   0.000001
8                        test_last_update_id_logic         0.000003   0.000001
9                              test_new_user_input         0.000004   0.000001
10                                  test_ping_only         0.000003   0.000001
11                          test_presence_disabled         0.000008   0.000003
12                               test_query_counts         0.000003   0.000001
13                                 test_same_realm         0.000003   0.000001
14                            test_single_user_get         0.000005   0.000002
15  test_user_presence_row_creation_simulated_race         0.000003   0.000001

In [3]:
print(with_legacy_format_average_df.to_latex())

\begin{tabular}{llrr}
\toprule
 & project_name & energy_consumed & emissions \\
\midrule
0 & test_date_logic & 0.000003 & 0.000001 \\
1 & test_do_change_user_setting_presence_enabled & 0.000003 & 0.000001 \\
2 & test_email_access & 0.000003 & 0.000001 \\
3 & test_filter_presence_idle_user_ids & 0.000003 & 0.000001 \\
4 & test_history_limit_days_api & 0.000003 & 0.000001 \\
5 & test_invalid_presence & 0.000003 & 0.000001 \\
6 & test_last_update_id_api & 0.000004 & 0.000001 \\
7 & test_last_update_id_api_no_data_edge_cases & 0.000003 & 0.000001 \\
8 & test_last_update_id_logic & 0.000003 & 0.000001 \\
9 & test_new_user_input & 0.000004 & 0.000001 \\
10 & test_ping_only & 0.000003 & 0.000001 \\
11 & test_presence_disabled & 0.000008 & 0.000003 \\
12 & test_query_counts & 0.000003 & 0.000001 \\
13 & test_same_realm & 0.000003 & 0.000001 \\
14 & test_single_user_get & 0.000005 & 0.000002 \\
15 & test_user_presence_row_creation_simulated_race & 0.000003 & 0.000001 \\
\bottomrule
\end{tabular}

In [4]:
dfs = []

for f in os.listdir("without_legacy_format"):
    if f.endswith(".csv"):
        df = pd.read_csv(f"without_legacy_format/{f}", sep=",", dtype={"energy_consumed": float, "emissions": float})
        dfs.append(df)

without_legacy_format_dfs = pd.concat(dfs)
without_legacy_format_dfs.head()

without_legacy_format_average_df = without_legacy_format_dfs.groupby("project_name")[["energy_consumed", "emissions"]].mean().reset_index()
without_legacy_format_average_df.head(20)

                                      project_name  energy_consumed  emissions
0                                  test_date_logic         0.000003   0.000001
1     test_do_change_user_setting_presence_enabled         0.000003   0.000001
2                                test_email_access         0.000003   0.000001
3               test_filter_presence_idle_user_ids         0.000003   0.000001
4                      test_history_limit_days_api         0.000003   0.000001
5                            test_invalid_presence         0.000003   0.000001
6                          test_last_update_id_api         0.000004   0.000001
7       test_last_update_id_api_no_data_edge_cases         0.000003   0.000001
8                        test_last_update_id_logic         0.000003   0.000001
9                              test_new_user_input         0.000004   0.000001
10                                  test_ping_only         0.000003   0.000001
11                          test_presence_disabled         0.000008   0.000003
12                               test_query_counts         0.000003   0.000001
13                                 test_same_realm         0.000003   0.000001
14                            test_single_user_get         0.000005   0.000002
15  test_user_presence_row_creation_simulated_race         0.000003   0.000001

In [5]:
print(without_legacy_format_average_df.to_latex())

\begin{tabular}{llrr}
\toprule
 & project_name & energy_consumed & emissions \\
\midrule
0 & test_date_logic & 0.000003 & 0.000001 \\
1 & test_do_change_user_setting_presence_enabled & 0.000003 & 0.000001 \\
2 & test_email_access & 0.000003 & 0.000001 \\
3 & test_filter_presence_idle_user_ids & 0.000003 & 0.000001 \\
4 & test_history_limit_days_api & 0.000003 & 0.000001 \\
5 & test_invalid_presence & 0.000003 & 0.000001 \\
6 & test_last_update_id_api & 0.000004 & 0.000001 \\
7 & test_last_update_id_api_no_data_edge_cases & 0.000003 & 0.000001 \\
8 & test_last_update_id_logic & 0.000003 & 0.000001 \\
9 & test_new_user_input & 0.000004 & 0.000001 \\
10 & test_ping_only & 0.000003 & 0.000001 \\
11 & test_presence_disabled & 0.000008 & 0.000003 \\
12 & test_query_counts & 0.000003 & 0.000001 \\
13 & test_same_realm & 0.000003 & 0.000001 \\
14 & test_single_user_get & 0.000005 & 0.000002 \\
15 & test_user_presence_row_creation_simulated_race & 0.000003 & 0.000001 \\
\bottomrule
\end{tabular}

In [6]:
difference = with_legacy_format_average_df[['project_name']].copy()
difference[["energy_consumed", "emissions"]] = with_legacy_format_average_df[["energy_consumed", "emissions"]] - without_legacy_format_average_df[["energy_consumed", "emissions"]]
difference.head(20)

,project_name,energy_consumed,emissions
0,test_date_logic,1.090470e-09,4.025299e-10
1,test_do_change_user_setting_presence_enabled,5.236919e-09,1.933127e-09
2,test_email_access,4.830488e-09,1.783099e-09
3,test_filter_presence_idle_user_ids,4.956090e-09,1.829463e-09
4,test_history_limit_days_api,2.334242e-09,8.616488e-10
5,test_invalid_presence,1.536116e-10,5.670334e-11
6,test_last_update_id_api,4.062169e-09,1.499486e-09
7,test_last_update_id_api_no_data_edge_cases,-4.615805e-09,-1.703852e-09
8,test_last_update_id_logic,-4.449758e-09,-1.642559e-09
9,test_new_user_input,-2.778391e-08,-1.025600e-08
10,test_ping_only,5.005809e-09,1.847816e-09
11,test_presence_disabled,1.157924e-08,4.274296e-09
12,test_query_counts,-3.283129e-09,-1.211916e-09
13,test_same_realm,-7.817534e-09,-2.885721e-09
14,test_single_user_get,4.636243e-08,1.711397e-08
15,test_user_presence_row_creation_simulated_race,1.252167e-09,4.622177e-10

In [7]:
print(difference.to_latex())

\begin{tabular}{llrr}
\toprule
 & project_name & energy_consumed & emissions \\
\midrule
0 & test_date_logic & 0.000000 & 0.000000 \\
1 & test_do_change_user_setting_presence_enabled & 0.000000 & 0.000000 \\
2 & test_email_access & 0.000000 & 0.000000 \\
3 & test_filter_presence_idle_user_ids & 0.000000 & 0.000000 \\
4 & test_history_limit_days_api & 0.000000 & 0.000000 \\
5 & test_invalid_presence & 0.000000 & 0.000000 \\
6 & test_last_update_id_api & 0.000000 & 0.000000 \\
7 & test_last_update_id_api_no_data_edge_cases & -0.000000 & -0.000000 \\
8 & test_last_update_id_logic & -0.000000 & -0.000000 \\
9 & test_new_user_input & -0.000000 & -0.000000 \\
10 & test_ping_only & 0.000000 & 0.000000 \\
11 & test_presence_disabled & 0.000000 & 0.000000 \\
12 & test_query_counts & -0.000000 & -0.000000 \\
13 & test_same_realm & -0.000000 & -0.000000 \\
14 & test_single_user_get & 0.000000 & 0.000000 \\
15 & test_user_presence_row_creation_simulated_race & 0.000000 & 0.000000 \\
\bottomrule
\end{tabular}

In [8]:
difference_in_percentage = with_legacy_format_average_df[['project_name']].copy()
difference_in_percentage[["energy_consumed", "emissions"]] = ((with_legacy_format_average_df[["energy_consumed", "emissions"]] - without_legacy_format_average_df[["energy_consumed", "emissions"]]) / with_legacy_format_average_df[["energy_consumed", "emissions"]]) * 100
difference_in_percentage = difference_in_percentage.rename(
    columns={
        "energy_consumed": "energy_consumed_percentage_change",
        "emissions": "emissions_percentage_change"
    }
)
difference_in_percentage["energy_consumed_percentage_change"] = difference_in_percentage["energy_consumed_percentage_change"].round(1).astype(str) + "%"
difference_in_percentage["emissions_percentage_change"] = difference_in_percentage["emissions_percentage_change"].round(1).astype(str) + "%"
difference_in_percentage.head(20)

,project_name,energy_consumed_percentage_change,emissions_percentage_change
0,test_date_logic,0.0%,0.0%
1,test_do_change_user_setting_presence_enabled,0.2%,0.2%
2,test_email_access,0.1%,0.1%
3,test_filter_presence_idle_user_ids,0.1%,0.1%
4,test_history_limit_days_api,0.1%,0.1%
5,test_invalid_presence,0.0%,0.0%
6,test_last_update_id_api,0.1%,0.1%
7,test_last_update_id_api_no_data_edge_cases,-0.1%,-0.1%
8,test_last_update_id_logic,-0.1%,-0.1%
9,test_new_user_input,-0.8%,-0.8%
10,test_ping_only,0.2%,0.2%
11,test_presence_disabled,0.2%,0.2%
12,test_query_counts,-0.1%,-0.1%
13,test_same_realm,-0.2%,-0.2%
14,test_single_user_get,0.9%,0.9%
15,test_user_presence_row_creation_simulated_race,0.0%,0.0%

In [9]:
print(difference_in_percentage.to_latex())

\begin{tabular}{llll}
\toprule
 & project_name & energy_consumed_percentage_change & emissions_percentage_change \\
\midrule
0 & test_date_logic & 0.0% & 0.0% \\
1 & test_do_change_user_setting_presence_enabled & 0.2% & 0.2% \\
2 & test_email_access & 0.1% & 0.1% \\
3 & test_filter_presence_idle_user_ids & 0.1% & 0.1% \\
4 & test_history_limit_days_api & 0.1% & 0.1% \\
5 & test_invalid_presence & 0.0% & 0.0% \\
6 & test_last_update_id_api & 0.1% & 0.1% \\
7 & test_last_update_id_api_no_data_edge_cases & -0.1% & -0.1% \\
8 & test_last_update_id_logic & -0.1% & -0.1% \\
9 & test_new_user_input & -0.8% & -0.8% \\
10 & test_ping_only & 0.2% & 0.2% \\
11 & test_presence_disabled & 0.2% & 0.2% \\
12 & test_query_counts & -0.1% & -0.1% \\
13 & test_same_realm & -0.2% & -0.2% \\
14 & test_single_user_get & 0.9% & 0.9% \\
15 & test_user_presence_row_creation_simulated_race & 0.0% & 0.0% \\
\bottomrule
\end{tabular}